app:
  name: test_app
  mode: dev
  static_path: ./statics

server:
  port: 8080
  prefix: /api

log:
  level: info
  path: /web_app/logs
  filename: web_app.log
  max_size: 20
  max_age: 30
  max_backups: 5


